version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - stock-frontend-network

networks:
  stock-frontend-network:
    driver: bridge
