version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-backend
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor
    networks:
      - stock-network

  nginx:
    image: nginx:alpine
    container_name: stock-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - stock-network

  database:
    image: mysql:8.0
    container_name: stock-db
    restart: always
    environment:
      MYSQL_DATABASE: stock
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stock-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - nginx
    networks:
      - stock-network
    environment:
      - NODE_ENV=development

networks:
  stock-network:
    driver: bridge

volumes:
  db-data:
